r"""Inverse-pole-figure (IPF) orientation colouring: the colour of a grain is
set by the crystal direction that lies along a chosen sample direction,
reduced into the fundamental sector of the crystal's symmetry.

Pipeline, per orientation ``R`` (crystal axes as columns, in the sample frame,
as in :mod:`crystallite.microstructure`, so ``v_crystal = R^T v_sample``):

1. crystal direction ``d = R^T s`` of the sample direction ``s``;
2. symmetry reduction: of the images ``S d`` over the symmetry operations
   ``S``, keep the one closest to a fixed reference direction (a Dirichlet
   cell of the group, which is a fundamental sector for any point group);
3. colour, from the position of the reduced direction in the sector.

Directions are Cartesian, in the crystal frame. To colour Miller indices,
convert them with :class:`crystallite.material.lattice.Lattice` first: plane
normals ``lattice.plane_normals(hkl)`` or lattice directions
``lattice.directions(uvw)`` (raw indices are the right vectors only for cubic
crystals).

The symmetry is a point group (:func:`crystallite.material.symmetry.point_group_operations`,
standard setting: principal axis along z, secondary axis along x), applied at
one of three levels (``symmetry=``):

``"laue"`` (default)
    The point group with the inversion: directions ``d`` and ``-d`` share a
    colour, as they do in diffraction.
``"holohedry"``
    The highest point group of the crystal system (``m-3m``, ``6/mmm``, ...):
    the conventional EBSD colour keys, which merge directions that the
    crystal's own point group tells apart.
``"point_group"``
    The point group itself, so polar crystals keep ``d`` and ``-d`` apart.

**Colour keys.** A key must give symmetry-equivalent directions one colour and
vary continuously, also across the sector edges, where the directions on
either side are equivalent to directions just inside the sector [2]_.

A group generated by its mirror planes has a sector (a *chamber*) bounded by
mirrors on every side: a spherical triangle (``m-3m``, ``-43m``, ``6/mmm``,
``-6m2``, ``-62m``, ``4/mmm``, ``mmm``), a lune (``mm2``, ``3m``, ``4mm``,
``6mm``) or a hemisphere (``m``). Its colour key is white at the centre and
fully saturated on the edges, where no condition applies. On a triangle each
channel is linear in ``d``, 1 at its vertex and 0 on the opposite edge,
weighted so that the centroid is white, then normalized by the largest
channel [1]_. On a lune or a hemisphere, the hue is the azimuth about the
centre and the saturation the fraction of the way to the edge.

Any other group ``G`` has sector edges joined by rotations. If it is an
index-2 subgroup of a mirror-generated group ``G'``, its sector is two
chambers of ``G'``, a chamber ``C`` and its mirror image across a mirror of
``G'`` outside ``G``. Each direction is reduced into ``C`` by ``G'``,
recording whether that took an operation outside ``G``. Directions that did
not are coloured by the white key of ``C``; directions that did are coloured
by its black counterpart (the white key less its grey part: the same hue,
black at the centre). The two keys agree on the edges of ``C``, so the colours
are continuous everywhere [2]_. This covers every point group except ``-1``,
``-3`` and ``-4``. These reverse orientation without mirrors, so identifying
equivalent directions turns the sphere into a projective plane, which does
not fit one-to-one into the 3D colour space [2]_. They are coloured by the key
of their proper rotation subgroup (``1``, ``3`` and ``4``) instead: still one
colour per orientation, since orientations are only defined up to the proper
rotations, but ``d`` and ``-d`` get different colours. This applies to
triclinic crystals at every level, and to point groups ``3`` and ``-3`` at
the ``"laue"`` level.

Sectors of polar groups reach into the lower hemisphere. Plots show them as
two stereographic panels side by side: the upper hemisphere projected from the
-z pole, the lower one from the +z pole.

References
----------
.. [1] O. Engler and V. Randle, *Introduction to Texture Analysis:
   Macrotexture, Microtexture, and Orientation Mapping*, 2nd ed., CRC Press
   (2010).
.. [2] G. Nolze and R. Hielscher, "Orientations -- perfectly colored",
   *J. Appl. Cryst.* **49**, 1786-1802 (2016).
"""

from __future__ import annotations

from functools import lru_cache
from itertools import combinations

import numpy as np

from crystallite.material.symmetry import (
    crystal_system,
    holohedry,
    laue_class,
    point_group_operations,
)

SAMPLE_DIRECTIONS = {"x": (1.0, 0.0, 0.0), "y": (0.0, 1.0, 0.0), "z": (0.0, 0.0, 1.0)}

_SYMMETRY_LEVELS = ("laue", "holohedry", "point_group")

# Picks the sector: off every symmetry element of every group in the standard
# setting, and inside the conventional triangles (0 <= y <= x <= z for m-3m,
# azimuth below 30 degrees for 6/mmm, ...).
_REFERENCE = np.array([0.3, 0.1, 1.0]) / np.linalg.norm([0.3, 0.1, 1.0])

_TOL = 1e-9


def _host(array):
    """NumPy copy of a NumPy or CuPy array."""
    return array.get() if hasattr(array, "get") else np.asarray(array, dtype=float)


def _normalize(vectors):
    vectors = np.asarray(vectors, dtype=float)
    return vectors / np.linalg.norm(vectors, axis=-1, keepdims=True)


def sample_direction(direction):
    """Unit sample direction from ``"x"``, ``"y"``, ``"z"`` or a 3-vector."""
    if isinstance(direction, str):
        try:
            direction = SAMPLE_DIRECTIONS[direction.lower()]
        except KeyError:
            raise ValueError(f"sample direction must be 'x', 'y', 'z' or a vector, got {direction!r}")
    return _normalize(direction)


def crystal_directions(rotations, direction="z"):
    """Crystal-frame components ``R^T s`` of the sample direction `direction`
    for each rotation in `rotations` (shape ``(..., 3, 3)``, crystal axes as
    columns). Returns shape ``(..., 3)``."""
    return np.einsum("...ji,j->...i", np.asarray(rotations, dtype=float), sample_direction(direction))


def _reduce(directions, operations, reference=_REFERENCE):
    """Image of each direction closest to `reference`, and the index of the
    operation that produced it."""
    images = np.einsum("nij,...j->...ni", _host(operations), np.asarray(directions, dtype=float))
    best = np.argmax(images @ np.asarray(reference, dtype=float), axis=-1)
    return np.take_along_axis(images, best[..., None, None], axis=-2)[..., 0, :], best


def reduce_directions(directions, operations, reference=_REFERENCE):
    """Symmetry-equivalent image of each direction closest to `reference`.

    The result lies in the Dirichlet cell of `reference`, a fundamental sector
    of the group: every direction equivalent under `operations` reduces to
    the same one (up to ties on the sector edges, whose images are equivalent
    there).

    Parameters
    ----------
    directions : array_like of shape (..., 3)
    operations : array_like of shape (n, 3, 3)
        A point group's operations (:func:`symmetry_operations`).
    reference : array_like of shape (3,)
        Must not lie on a symmetry element.

    Returns
    -------
    ndarray of shape (..., 3)
    """
    return _reduce(directions, operations, reference)[0]


def symmetry_group(point_group, symmetry="laue"):
    """Point group applied at a symmetry level: the point group's Laue class
    (``"laue"``), its crystal system's holohedry (``"holohedry"``) or the
    point group itself (``"point_group"``)."""
    if symmetry == "laue":
        return laue_class(point_group)
    if symmetry == "holohedry":
        return holohedry(point_group)
    if symmetry == "point_group":
        point_group_operations(point_group)  # validates point_group
        return point_group
    raise ValueError(f"symmetry must be one of {_SYMMETRY_LEVELS}, got {symmetry!r}")


def symmetry_operations(point_group, symmetry="laue"):
    """Operations of :func:`symmetry_group`, a NumPy array ``(n, 3, 3)``."""
    return _host(point_group_operations(symmetry_group(point_group, symmetry)))


# --- groups and chambers ----------------------------------------------------


def _key(op):
    return tuple(np.round(op, 6).ravel() + 0.0)


def _is_mirror(op):
    return np.linalg.det(op) < 0 and abs(np.trace(op) - 1.0) < 1e-6


def _reflect(vectors, normal):
    """Mirror image of `vectors` across the plane of unit `normal`."""
    vectors = np.asarray(vectors, dtype=float)
    return vectors - 2.0 * (vectors @ normal)[..., None] * normal


def _generated(generators):
    """Operations of the group generated by `generators`."""
    identity = np.eye(3)
    ops, seen, frontier = [identity], {_key(identity)}, [identity]
    while frontier:
        new = []
        for op in frontier:
            for generator in generators:
                product = generator @ op
                if _key(product) not in seen:
                    seen.add(_key(product))
                    new.append(product)
        ops += new
        frontier = new
    return np.array(ops)


def _is_mirror_group(operations):
    """Whether the group has mirrors and is generated by them."""
    mirrors = [op for op in operations if _is_mirror(op)]
    return bool(mirrors) and len(_generated(mirrors)) == len(operations)


def _mirror_normals(operations):
    """Unit normals of the mirror planes among `operations`, oriented towards
    the reference direction."""
    normals = []
    for op in operations:
        if _is_mirror(op):
            # op = I - 2 n n^T
            projector = (np.eye(3) - op) / 2.0
            n = projector[:, np.argmax(np.linalg.norm(projector, axis=0))]
            n = n / np.linalg.norm(n)
            normals.append(n if n @ _REFERENCE > 0 else -n)
    return np.array(normals).reshape(-1, 3)


def _great_circle(normal, n=720):
    """`n` points around the great circle normal to unit `normal`."""
    a = np.cross(normal, (1.0, 0.0, 0.0) if abs(normal[0]) < 0.9 else (0.0, 1.0, 0.0))
    a /= np.linalg.norm(a)
    b = np.cross(normal, a)
    t = np.linspace(0.0, 2.0 * np.pi, n, endpoint=False)[:, None]
    return np.cos(t) * a + np.sin(t) * b


def _unique_directions(vectors, tol=1e-9):
    unique = []
    for v in np.asarray(vectors, dtype=float).reshape(-1, 3):
        if not any(np.allclose(v, u, atol=tol) for u in unique):
            unique.append(v)
    return np.array(unique).reshape(-1, 3)


def _walls(normals):
    """The normals whose planes bound the region ``n . d >= 0`` (for every
    one of `normals`) along an arc, i.e. without duplicates and redundant
    half-spaces."""
    normals = _unique_directions(normals)
    walls = []
    for i, n in enumerate(normals):
        others = np.delete(normals, i, axis=0)
        if np.any(np.all(_great_circle(n) @ others.T > _TOL, axis=-1)):
            walls.append(n)
    return np.array(walls).reshape(-1, 3)


def _chamber_vertices(normals):
    """Vertices of the region ``n . d >= 0`` for every mirror normal ``n``."""
    vertices = []
    for a, b in combinations(normals, 2):
        cross = np.cross(a, b)
        if np.linalg.norm(cross) < 1e-9:
            continue
        for candidate in (cross, -cross):
            candidate = candidate / np.linalg.norm(candidate)
            if np.all(normals @ candidate > -1e-9) and not any(
                np.allclose(candidate, v, atol=1e-9) for v in vertices
            ):
                vertices.append(candidate)
    return np.array(vertices).reshape(-1, 3)


def _chamber_center(walls):
    """White point of a chamber: the area centroid of a triangle, else the
    direction equidistant from the walls of a lune or hemisphere."""
    vertices = _chamber_vertices(walls)
    if len(vertices) == 3:
        return spherical_triangle_centroid(vertices)
    return _normalize(walls.sum(axis=0))


def _lattice_mirrors(group):
    """Mirrors of the lattice holohedry of `group`'s crystal family (6/mmm
    or m-3m, in the standard setting): the candidates for extending it."""
    lattice = "6/mmm" if crystal_system(group) in ("trigonal", "hexagonal") else "m-3m"
    return [op for op in _host(point_group_operations(lattice)) if _is_mirror(op)]


def _colouring_group(operations, candidates):
    """Mirror group that colours a point group and the mirror that doubles
    its chamber into the point group's sector.

    Returns ``(operations, None)`` for a group generated by its mirrors;
    otherwise ``(extended, normal)`` where `extended` lists the group's
    operations followed by their products with a mirror of `candidates`
    (an index-2 mirror-generated supergroup) and `normal` is the unit normal
    of a chamber wall whose mirror lies outside the group. Of the
    possibilities, the sector nearest the crystal z axis wins (then the one
    extending counterclockwise, then the one centred nearest azimuth 0).
    Returns ``(None, None)`` if there is none.
    """
    if _is_mirror_group(operations):
        return operations, None
    known = {_key(op) for op in operations}
    best, best_score = (None, None), None
    for mirror in candidates:
        if _key(mirror) in known or {_key(mirror @ op @ mirror) for op in operations} != known:
            continue  # in the group, or does not normalize it
        extended = np.concatenate([operations, mirror @ operations])
        if not _is_mirror_group(extended):
            continue
        walls = _walls(_mirror_normals(extended))
        white = _chamber_center(walls)
        for normal in walls:
            if _key(np.eye(3) - 2.0 * np.outer(normal, normal)) in known:
                continue
            black = _reflect(white, normal)
            score = np.round(
                [white[2] + black[2], white[2], np.cross(white, black)[2], -abs(np.arctan2(white[1], white[0]))],
                6,
            ).tolist()
            if best_score is None or score > best_score:
                best, best_score = (extended, normal), score
    return best


def _slerp(a, b, n):
    """`n` points along the great-circle arc from `a` to `b`."""
    angle = np.arccos(np.clip(a @ b, -1.0, 1.0))
    t = np.linspace(0.0, 1.0, n)[:, None]
    return (np.sin((1 - t) * angle) * a + np.sin(t * angle) * b) / np.sin(angle)


def spherical_triangle_area(vertices):
    """Area (spherical excess) of the spherical triangle with unit `vertices`
    (Van Oosterom and Strackee)."""
    a, b, c = _normalize(vertices)
    return 2.0 * np.arctan2(abs(a @ np.cross(b, c)), 1.0 + a @ b + b @ c + c @ a)


def spherical_triangle_centroid(vertices):
    r"""Unit direction of the area centroid of a spherical triangle,
    :math:`\int d\,dA \propto \sum_{\text{edges }ab}\theta_{ab}\,
    \widehat{a\times b}` (edges counterclockwise seen from outside)."""
    v = _normalize(vertices)
    if np.linalg.det(v) < 0:
        v = v[::-1]
    total = np.zeros(3)
    for a, b in zip(v, np.roll(v, -1, axis=0)):
        cross = np.cross(a, b)
        total += np.arccos(np.clip(a @ b, -1.0, 1.0)) * cross / np.linalg.norm(cross)
    return total / np.linalg.norm(total)


def _integer_indices(values, tol=1e-6):
    values = np.asarray(values, dtype=float)
    base = values / np.abs(values[np.abs(values) > tol]).min()
    for multiple in range(1, 7):
        scaled = base * multiple
        if np.allclose(scaled, np.round(scaled), atol=1e-4):
            return np.round(scaled).astype(int)
    return np.round(values / np.abs(values).max(), 2)  # irrational: largest index 1


def miller_label(direction, hexagonal=False, lattice=None, plane=False, brackets=False):
    r"""Miller indices of a Cartesian `direction` as a TeX string (bars for
    negative indices), in ``[uvw]`` or, if `plane`, ``(hkl)`` brackets if
    `brackets`.

    Without a `lattice`, the indices are the direction's components along
    orthonormal crystal axes: three-index ``[uvw]``, or four-index
    Miller--Bravais ``[uvtw]`` with :math:`a_1` along x (and :math:`c/a=1`)
    when `hexagonal`. That labels the sector vertices of every system but
    monoclinic and triclinic exactly: each lies along a crystal axis, in a
    basal or prism plane, or along a cube diagonal, where direction and
    plane-normal indices coincide for any cell.

    With a :class:`~crystallite.material.lattice.Lattice`, the indices are
    those of the lattice direction along `direction` (``[uvw]``), or if
    `plane` of the plane normal to it (``(hkl)``); four-index if the lattice
    has hexagonal axes. Irrational indices are shown to two decimals.
    """
    d = _normalize(direction)
    if lattice is not None:
        hexagonal = lattice.is_hexagonal
        if plane:  # (hkl) = A^T n
            h, k, l = d @ lattice.direct
            values = [h, k, -(h + k), l] if hexagonal else [h, k, l]
        else:  # [uvw] = A^-1 d
            u, v, w = np.linalg.solve(lattice.direct, d)
            values = [(2 * u - v) / 3, (2 * v - u) / 3, -(u + v) / 3, w] if hexagonal else [u, v, w]
    elif hexagonal:
        basal = np.array([[1.0, 0.0], [-0.5, 3**0.5 / 2], [-0.5, -(3**0.5) / 2]])
        values = [*(2.0 / 3.0 * basal @ d[:2]), d[2]]
    else:
        values = d
    indices = _integer_indices(values)
    if np.issubdtype(indices.dtype, np.integer):
        text = "".join(rf"\bar{{{-i}}}" if i < 0 else str(i) for i in indices)
    else:
        parts = [f"{abs(i):.2f}".rstrip("0").rstrip(".") for i in indices]
        text = r"\,".join(rf"\bar{{{p}}}" if i < 0 else p for i, p in zip(indices, parts))
    if brackets:
        text = f"({text})" if plane else f"[{text}]"
    return f"${text}$"


def _hsv_to_rgb(hue, saturation, value):
    """RGB of HSV colours, all channels in [0, 1]."""
    k = (np.array([5.0, 3.0, 1.0]) + 6.0 * np.asarray(hue)[..., None]) % 6.0
    value, saturation = np.asarray(value)[..., None], np.asarray(saturation)[..., None]
    return value - value * saturation * np.clip(np.minimum(k, 4.0 - k), 0.0, 1.0)


def _order_vertices(vertices):
    """The vertex nearest the crystal z axis first, the rest by increasing
    azimuth."""
    if len(vertices) == 0:
        return vertices
    first = np.argmax(vertices[:, 2])
    others = [i for i in range(len(vertices)) if i != first]
    others.sort(key=lambda i: np.arctan2(vertices[i, 1], vertices[i, 0]))
    return vertices[[first, *others]]


def _fibonacci_sphere(n):
    """`n` nearly uniform unit directions."""
    i = np.arange(n) + 0.5
    z = 1.0 - 2.0 * i / n
    phi = np.pi * (1.0 + 5**0.5) * i
    r = np.sqrt(1.0 - z * z)
    return np.stack([r * np.cos(phi), r * np.sin(phi), z], axis=-1)


# Groups with no continuous one-to-one key, and the proper rotation subgroup
# coloured in their place.
_PROPER_FALLBACK = {"-1": "1", "-3": "3", "-4": "4"}

_HEMISPHERES = {"upper": np.array([0.0, 0.0, 1.0]), "lower": np.array([0.0, 0.0, -1.0])}


class InversePoleFigure:
    r"""Fundamental sector and IPF colour key of a point group.

    Parameters
    ----------
    point_group : str
        One of the 32 point groups, e.g. ``"m-3m"``, ``"6/mmm"``, ``"-43m"``.
    symmetry : {"laue", "holohedry", "point_group"}
        Level at which the point group's symmetry is applied (see the module
        docstring).
    lattice : Lattice, optional
        The crystal's :class:`~crystallite.material.lattice.Lattice`, for
        exact corner labels (see :func:`miller_label`). It changes no colour.
    indices : {None, "directions", "planes"}
        Label the corners by lattice directions ``[uvw]`` or by the planes
        ``(hkl)`` normal to them, in brackets; None gives bare direction
        indices. The key labels :meth:`label_points`.

    Attributes
    ----------
    group : str
        The point group whose operations reduce the directions: the one set
        by `symmetry`, or for ``-1``, ``-3`` and ``-4`` its proper rotation
        subgroup ``1``, ``3`` or ``4`` (see the module docstring).
    operations : ndarray of shape (n, 3, 3)
    mirror : ndarray of shape (3,) or None
        Normal of the mirror that splits the sector into a white and a black
        half, or None for a group generated by its mirrors (all white).
    walls : ndarray of shape (k, 3)
        Inward unit normals of the great circles that bound the sector (none
        for point group ``1``, whose sector is the whole sphere).
    vertices : ndarray of shape (m, 3)
        Sector corners, the one nearest the crystal z axis first, the rest by
        increasing azimuth: for a triangle bounded by mirrors, the red, green
        and blue vertices.
    labels : list of str
        Miller indices of the vertices (:meth:`label`); the key itself
        labels :meth:`label_points`.
    white_point : ndarray of shape (3,)
        Centre of the white half (the area centroid for a triangle).
    black_point : ndarray of shape (3,) or None
        Centre of the black half.
    hemispheres : tuple of str
        ``("upper",)``, or ``("upper", "lower")`` for a sector that reaches
        into the lower hemisphere.
    """

    def __init__(self, point_group, symmetry="laue", lattice=None, indices=None):
        self.point_group = point_group
        self.symmetry = symmetry
        group = symmetry_group(point_group, symmetry)
        self.group = _PROPER_FALLBACK.get(group, group)
        self.operations = _host(point_group_operations(self.group))
        if indices not in (None, "directions", "planes"):
            raise ValueError(f"indices must be None, 'directions' or 'planes', got {indices!r}")
        if lattice is not None and not lattice.is_compatible(self.group):
            raise ValueError(f"{lattice!r} is not invariant under point group {self.group!r}")
        self.lattice = lattice
        self.indices = indices

        extended, self.mirror = _colouring_group(self.operations, _lattice_mirrors(self.group))
        if extended is None:
            raise RuntimeError(f"no colour key for point group {self.group!r}")
        self._extended = extended
        self._black = np.arange(len(extended)) >= len(self.operations)

        # The white half: a chamber of the mirror group.
        self._chamber_walls = _walls(_mirror_normals(extended))
        chamber = _chamber_vertices(self._chamber_walls)
        self._triangle = len(chamber) == 3
        self.white_point = _chamber_center(self._chamber_walls)
        if self._triangle:
            corners = _order_vertices(chamber)
            # Row i: normal of the edge opposite vertex i, scaled so that it
            # evaluates to 1 at vertex i (and 0 on that edge).
            planes = np.cross(np.roll(corners, -1, axis=0), np.roll(corners, -2, axis=0))
            self._planes = planes / np.einsum("ij,ij->i", planes, corners)[:, None]
            self._weights = 1.0 / (self._planes @ self.white_point)
        else:
            # Hue reference: towards the crystal z axis (x if the centre is on it).
            for axis in np.eye(3)[[2, 0]]:
                tangent = axis - (axis @ self.white_point) * self.white_point
                if np.linalg.norm(tangent) > 1e-6:
                    break
            self._east = tangent / np.linalg.norm(tangent)
            self._north = np.cross(self.white_point, self._east)

        # The sector: the chamber and, across the mirror, its black image.
        if self.mirror is None:
            self.black_point = None
            self.walls = self._chamber_walls
        else:
            self.black_point = _reflect(self.white_point, self.mirror)
            kept = [n for n in self._chamber_walls if abs(abs(n @ self.mirror) - 1.0) > 1e-9]
            self.walls = _walls(kept + [_reflect(n, self.mirror) for n in kept])

        self.vertices = _order_vertices(_chamber_vertices(self.walls))
        self._hexagonal = crystal_system(self.group) in ("trigonal", "hexagonal")
        self.labels = [self.label(v) for v in self.vertices]

        probe = _fibonacci_sphere(4096)
        inside = np.all(probe @ self.walls.T > 1e-3, axis=-1) & (probe[:, 2] < -1e-3)
        self.hemispheres = ("upper", "lower") if inside.any() else ("upper",)

    @classmethod
    def from_solid(cls, solid, symmetry="laue", indices=None):
        """Key of a :class:`~crystallite.material.properties.Solid`: its point
        group, and its lattice (if set) for the labels."""
        return cls(solid.point_group, symmetry, solid.lattice, indices)

    def __repr__(self):
        extra ="" if self.lattice is None else f", lattice={self.lattice!r}, indices={self.indices!r}"
        return f"InversePoleFigure({self.point_group!r}, symmetry={self.symmetry!r}{extra})"

    def label(self, direction):
        """Miller indices of a direction as a TeX string (:func:`miller_label`,
        with this key's lattice and indices)."""
        return miller_label(
            direction, self._hexagonal, self.lattice, self.indices == "planes", self.indices is not None
        )

    def _chamber(self, directions):
        """Image of each unit direction in the white chamber, and whether it
        took an operation outside the group (the black half)."""
        reduced, index = _reduce(_normalize(directions), self._extended)
        return reduced, self._black[index]

    def reduce(self, directions):
        """Unit symmetry-equivalent of each direction inside the sector,
        shape ``(..., 3)``."""
        reduced, black = self._chamber(directions)
        if self.mirror is not None:
            reduced = np.where(black[..., None], _reflect(reduced, self.mirror), reduced)
        return reduced

    def contains(self, directions, tol=1e-9):
        """Whether each unit direction lies in the sector (without reduction)."""
        return np.all(np.asarray(directions, dtype=float) @ self.walls.T >= -tol, axis=-1)

    def _white(self, directions):
        """White key of unit directions in the chamber."""
        if self._triangle:
            channels = np.clip(directions @ self._planes.T, 0.0, None) * self._weights
            return channels / channels.max(axis=-1, keepdims=True)
        # Saturation: the fraction of the great-circle arc from the centre
        # through the direction to the chamber edge; hue: its azimuth.
        w = self.white_point
        cos = np.clip(directions @ w, -1.0, 1.0)
        tangent = directions - cos[..., None] * w
        length = np.linalg.norm(tangent, axis=-1, keepdims=True)
        u = np.where(length > 1e-12, tangent / np.where(length > 1e-12, length, 1.0), self._east)
        # A wall n is reached where cos(s) n.w + sin(s) n.u = 0.
        edge = np.arctan2(self._chamber_walls @ w, -(u @ self._chamber_walls.T)).min(axis=-1)
        saturation = np.clip(np.arccos(cos) / edge, 0.0, 1.0)
        hue = np.arctan2(u @ self._north, u @ self._east) / (2.0 * np.pi) % 1.0
        return _hsv_to_rgb(hue, saturation, np.ones_like(hue))

    def color(self, directions):
        """RGB in [0, 1] of each crystal direction, shape ``(..., 3)``."""
        reduced, black = self._chamber(directions)
        white = self._white(reduced)
        return np.where(black[..., None], white - white.min(axis=-1, keepdims=True), white)

    def project(self, directions):
        """Stereographic coordinates (:func:`stereographic`) of the reduced
        directions, shape ``(..., 2)``."""
        return stereographic(self.reduce(directions))

    def corners(self, hemisphere="upper"):
        """Corners of the part of the sector in `hemisphere`, including where
        its edges cross the equator."""
        walls = _unique_directions(np.concatenate([self.walls, _HEMISPHERES[hemisphere][None]]))
        return _order_vertices(_chamber_vertices(walls))

    def label_points(self, hemisphere="upper"):
        """Directions labelled on the key in `hemisphere`: the corners of the
        sector there, or for a monoclinic crystal the crystal axes on its
        edges whose indices hold for any monoclinic angle.

        Monoclinic sector corners (along x) only mark where the sector was
        cut, and x is the (100) normal but a lattice direction only when
        beta is 90 degrees. With c along z and the unique axis b along y,
        the exact labels are [001] and [010] as directions, or the normals
        of (100) and (010) as planes.
        """
        if crystal_system(self.group) != "monoclinic":
            return self.corners(hemisphere)
        axes = np.eye(3)[[0, 1] if self.indices == "planes" else [2, 1]]
        candidates = np.concatenate([axes, -axes])
        walls = _unique_directions(np.concatenate([self.walls, _HEMISPHERES[hemisphere][None]]))
        cosines = candidates @ walls.T
        on_edge = np.all(cosines >= -_TOL, axis=-1) & np.any(np.abs(cosines) < _TOL, axis=-1)
        return _order_vertices(candidates[on_edge])

    def outline(self, n=64, hemisphere="upper"):
        """Stereographic outline of the part of the sector in `hemisphere`
        (its edges, and the equator where it bounds that part), shape
        ``(m, 2)``, with rows of NaN between separate arcs."""
        walls = _unique_directions(np.concatenate([self.walls, _HEMISPHERES[hemisphere][None]]))
        corners = _chamber_vertices(walls)
        arcs = []
        for i, wall in enumerate(walls):
            others = np.delete(walls, i, axis=0)
            points = _great_circle(wall, 12 * n)
            inside = np.all(points @ others.T >= -_TOL, axis=-1)
            if inside.all():
                arcs.append(np.concatenate([points, points[:1]]))
                continue
            points, inside = np.roll(points, -np.argmin(inside), axis=0), np.roll(inside, -np.argmin(inside))
            ends = corners[np.abs(corners @ wall) < 1e-9]
            edges = np.flatnonzero(np.diff(np.append(inside, False).astype(int)))
            for start, stop in zip(edges[::2] + 1, edges[1::2] + 1):
                arc = points[start:stop]
                if len(ends):  # close the gaps to the exact corners
                    first = ends[np.argmax(ends @ arc[0])]
                    last = ends[np.argmax(ends @ arc[-1])]
                    arc = np.concatenate([first[None], arc, last[None]])
                arcs.append(arc)
        pieces = []
        for arc in arcs:
            pieces += [stereographic(arc), np.full((1, 2), np.nan)]
        return np.concatenate(pieces[:-1]) if pieces else np.empty((0, 2))

    def key_image(self, resolution=256, hemisphere="upper"):
        """Rasterized colour key: RGBA over the stereographic bounding box of
        the part of the sector in `hemisphere`, transparent outside it,
        coloured by :meth:`color`.

        Returns
        -------
        image : ndarray of shape (ny, nx, 4)
            Row 0 at the bottom (``imshow(..., origin="lower")``).
        extent : tuple
            ``(x0, x1, y0, y1)`` in stereographic coordinates.
        """
        outline = self.outline(hemisphere=hemisphere)
        (x0, y0), (x1, y1) = np.nanmin(outline, axis=0), np.nanmax(outline, axis=0)
        step = max(x1 - x0, y1 - y0) / resolution
        nx = max(int(np.ceil((x1 - x0) / step)), 1)
        ny = max(int(np.ceil((y1 - y0) / step)), 1)
        x = x0 + (np.arange(nx) + 0.5) * (x1 - x0) / nx
        y = y0 + (np.arange(ny) + 0.5) * (y1 - y0) / ny
        x, y = np.meshgrid(x, y)
        directions = inverse_stereographic(x, y, lower=hemisphere == "lower")
        image = np.zeros((ny, nx, 4))
        inside = self.contains(directions) & (x * x + y * y <= 1.0)
        image[inside, :3] = self.color(directions[inside])
        image[inside, 3] = 1.0
        return image, (x0, x1, y0, y1)


def stereographic(directions):
    """Stereographic coordinates of unit directions, each projected from the
    pole of the other hemisphere (the -z pole for the upper hemisphere, the
    +z pole for the lower one), so both fill the unit disk. Shape
    ``(..., 2)``."""
    d = np.asarray(directions, dtype=float)
    return d[..., :2] / (1.0 + np.abs(d[..., 2:3]))


def inverse_stereographic(x, y, lower=False):
    """Unit directions of stereographic coordinates (:func:`stereographic`)
    in the upper hemisphere, or the lower one if `lower`, shape
    ``x.shape + (3,)``."""
    x, y = np.asarray(x, dtype=float), np.asarray(y, dtype=float)
    r2 = x * x + y * y
    z = -(1.0 - r2) if lower else 1.0 - r2
    return np.stack([2.0 * x, 2.0 * y, z], axis=-1) / (1.0 + r2)[..., None]


@lru_cache(maxsize=None)
def inverse_pole_figure(point_group, symmetry="laue"):
    """Cached :class:`InversePoleFigure`."""
    return InversePoleFigure(point_group, symmetry)


def _as_ipf(ipf, symmetry="laue"):
    return ipf if isinstance(ipf, InversePoleFigure) else inverse_pole_figure(ipf, symmetry)


def ipf_color(directions, point_group, symmetry="laue"):
    """IPF colour of crystal directions (shape ``(..., 3)``) for a point group
    at a symmetry level; see :class:`InversePoleFigure`."""
    return inverse_pole_figure(point_group, symmetry).color(directions)


def orientation_colors(rotations, ipf, direction="z", symmetry="laue"):
    """IPF colour of each orientation along a sample direction.

    Parameters
    ----------
    rotations : array_like of shape (..., 3, 3)
        Crystal axes as columns, in the sample frame.
    ipf : InversePoleFigure or str
        The colour key, or a point group (with `symmetry`).
    direction : {"x", "y", "z"} or array_like of shape (3,)
        Sample direction.

    Returns
    -------
    ndarray of shape (..., 3)
    """
    return _as_ipf(ipf, symmetry).color(crystal_directions(rotations, direction))


def orientation_map(labels, rotations, ipf, direction="z", symmetry="laue"):
    """IPF-coloured image of a labelled microstructure: one colour per
    orientation, placed by the integer `labels`.

    Parameters
    ----------
    labels : array_like of int
        Index into `rotations` at every voxel: ``ms.grain_ids`` with
        ``ms.orientations``, ``ms.slot_field()`` with ``ms.slot_orientations``,
        or ``eta.argmax(axis=0)`` for order parameters ``eta`` that carry
        ``ms.slot_orientations``.
    rotations : array_like of shape (n, 3, 3)
    ipf, direction, symmetry
        As in :func:`orientation_colors`.

    Returns
    -------
    ndarray of shape ``labels.shape + (3,)``
    """
    return orientation_colors(rotations, ipf, direction, symmetry)[_host(labels).astype(int)]


# --- plotting ---------------------------------------------------------------


def _pyplot():
    try:
        import matplotlib.pyplot as plt
    except ImportError as error:
        raise ImportError("plotting requires the optional matplotlib dependency") from error
    return plt


def _panels(ipf, gap=1.3):
    """``(hemisphere, x offset)`` of each stereographic panel: the lower
    hemisphere, if needed, to the right of the upper one."""
    panels = [("upper", 0.0)]
    if "lower" in ipf.hemispheres:
        upper, lower = ipf.outline(hemisphere="upper"), ipf.outline(hemisphere="lower")
        span = np.nanmax(upper[:, 0]) - np.nanmin(upper[:, 0])
        panels.append(("lower", np.nanmax(upper[:, 0]) + gap * span - np.nanmin(lower[:, 0])))
    return panels


def _sector_axes(ipf, ax, labels=True):
    """Outline, corner labels and (with two panels) hemisphere names of the
    sector on `ax`."""
    panels = _panels(ipf)
    outlines = [ipf.outline(hemisphere=h) + (dx, 0.0) for h, dx in panels]
    points = np.concatenate(outlines)
    (x0, y0), (x1, y1) = np.nanmin(points, axis=0), np.nanmax(points, axis=0)
    span = max(x1 - x0, y1 - y0)
    for (hemisphere, dx), outline in zip(panels, outlines):
        ax.plot(outline[:, 0], outline[:, 1], color="k", linewidth=1.0)
        center = np.nanmean(outline, axis=0)
        if labels:
            for corner in ipf.label_points(hemisphere):
                point = stereographic(corner) + (dx, 0.0)
                offset = point - center
                norm = np.linalg.norm(offset)
                offset = offset / norm if norm > 1e-9 else np.array([0.0, 1.0])
                # anchor the label on its side facing the corner, so it grows away
                ha = "left" if offset[0] > 0.4 else "right" if offset[0] < -0.4 else "center"
                va = "bottom" if offset[1] > 0.4 else "top" if offset[1] < -0.4 else "center"
                ax.text(*(point + 0.03 * span * offset), ipf.label(corner), ha=ha, va=va)
        if len(panels) > 1:
            bottom = np.nanmin(outline[:, 1])
            ax.text(center[0], bottom - 0.15 * span, hemisphere, ha="center", va="top", style="italic")
    ax.set_xlim(x0 - 0.12 * span, x1 + 0.12 * span)
    ax.set_ylim(y0 - (0.25 if len(panels) > 1 else 0.12) * span, y1 + 0.12 * span)
    ax.set_aspect("equal")
    ax.set_axis_off()
    return ax


def plot_ipf_key(ipf, ax=None, resolution=256, labels=True, symmetry="laue"):
    """Draw the IPF colour key of `ipf` (an :class:`InversePoleFigure` or a
    point group), coloured by the same :meth:`InversePoleFigure.color` as the
    orientation maps. Returns the axes."""
    ipf = _as_ipf(ipf, symmetry)
    if ax is None:
        ax = _pyplot().subplots()[1]
    for hemisphere, dx in _panels(ipf):
        image, (x0, x1, y0, y1) = ipf.key_image(resolution, hemisphere)
        ax.imshow(image, origin="lower", extent=(x0 + dx, x1 + dx, y0, y1), interpolation="nearest")
    return _sector_axes(ipf, ax, labels)


def plot_ipf(rotations, ipf, direction="z", ax=None, labels=True, symmetry="laue", **scatter):
    """Scatter the sample direction `direction` of each orientation in the
    fundamental sector (an inverse pole figure). Extra keywords go to
    :meth:`matplotlib.axes.Axes.scatter`. Returns the axes."""
    ipf = _as_ipf(ipf, symmetry)
    if ax is None:
        ax = _pyplot().subplots()[1]
    reduced = ipf.reduce(crystal_directions(rotations, direction)).reshape(-1, 3)
    points = stereographic(reduced)
    offsets = dict(_panels(ipf))
    points[reduced[:, 2] < 0.0, 0] += offsets.get("lower", 0.0)
    scatter.setdefault("s", 12)
    ax.scatter(points[:, 0], points[:, 1], **scatter)
    return _sector_axes(ipf, ax, labels)


def _boundary_mask(labels):
    """Voxels whose label differs from a (periodic) neighbour's."""
    mask = np.zeros(labels.shape, dtype=bool)
    for axis in range(labels.ndim):
        if labels.shape[axis] > 1:
            mask |= labels != np.roll(labels, 1, axis=axis)
    return mask


def plot_orientation_map(
    labels,
    rotations,
    ipf,
    direction="z",
    ax=None,
    extent=None,
    boundaries=True,
    z_index=0,
    symmetry="laue",
):
    """Draw an IPF orientation map (see :func:`orientation_map`) of a 2D
    microstructure, or of the slice `z_index` of a 3D one, with x to the
    right and y up. `extent` is passed to ``imshow`` (e.g. ``(0, Lx, 0, Ly)``);
    `boundaries` blacks out voxels on label boundaries. Returns the axes."""
    labels = _host(labels).astype(int)
    if labels.ndim == 3:
        labels = labels[:, :, z_index]
    rgb = orientation_map(labels, rotations, ipf, direction, symmetry)
    if boundaries:
        rgb[_boundary_mask(labels)] = 0.0
    if ax is None:
        ax = _pyplot().subplots()[1]
    ax.imshow(np.swapaxes(rgb, 0, 1), origin="lower", extent=extent, interpolation="nearest")
    ax.set_xticks([])
    ax.set_yticks([])
    return ax


def plot_orientation_maps(
    labels, rotations, ipf, directions="xyz", key=True, extent=None, boundaries=True,
    z_index=0, symmetry="laue",
):
    """Orientation maps along several sample directions side by side, with
    the colour key. Returns ``(figure, axes)``."""
    ipf = _as_ipf(ipf, symmetry)
    plt = _pyplot()
    n = len(directions) + bool(key)
    figure, axes = plt.subplots(1, n, figsize=(3.2 * n, 3.4), squeeze=False)
    axes = axes[0]
    for ax, direction in zip(axes, directions):
        plot_orientation_map(
            labels, rotations, ipf, direction, ax=ax, extent=extent,
            boundaries=boundaries, z_index=z_index,
        )
        name = direction if isinstance(direction, str) else str(list(direction))
        ax.set_title(f"IPF-{name.upper()}")
    if key:
        plot_ipf_key(ipf, ax=axes[-1])
    figure.tight_layout()
    return figure, axes
