r"""Inverse-pole-figure (IPF) orientation colouring: the colour of a grain is
set by the crystal direction that lies along a chosen sample direction,
reduced into the fundamental sector of the crystal's symmetry.

Pipeline, per orientation ``R`` (crystal axes as columns, in the sample frame,
as in :mod:`crystallite.microstructure`, so ``v_crystal = R^T v_sample``):

1. crystal direction ``d = R^T s`` of the sample direction ``s``;
2. symmetry reduction: of the images ``S d`` over the symmetry operations
   ``S``, keep the one closest to a fixed reference direction (a Dirichlet
   cell of the group, which is a fundamental sector for any point group);
3. colour: with the sector a spherical triangle of vertices
   :math:`v_R, v_G, v_B`, each channel is linear in ``d``, 1 at its vertex and
   0 on the opposite edge, weighted so that the sector's centroid is white,
   then normalized by the largest channel [1]_.

The symmetry is a point group (:func:`crystallite.material.symmetry.point_group_operations`,
standard setting: principal axis along z, secondary axis along x), applied at
one of three levels (``symmetry=``):

``"laue"`` (default)
    The point group with the inversion: directions ``d`` and ``-d`` share a
    colour, as they do in diffraction.
``"holohedry"``
    The highest point group of the crystal system (``m-3m``, ``6/mmm``, ...):
    the conventional EBSD colour keys, which merge directions that the
    crystal's own point group tells apart.
``"point_group"``
    The point group itself, so polar crystals keep ``d`` and ``-d`` apart.

Only groups generated by their mirror planes have a sector bounded by mirrors
on every side, where the linear colouring is continuous across the sector
edges. With a triangular sector these are ``m-3m``, ``4/mmm``, ``6/mmm`` and
``mmm`` among the Laue classes (so every cubic, tetragonal, hexagonal and
orthorhombic point group at the ``"laue"`` and ``"holohedry"`` levels), plus
``-43m``, ``-6m2`` and ``-62m`` at the ``"point_group"`` level. The others
(trigonal, monoclinic and triclinic crystals, and polar groups at the
``"point_group"`` level) have sector edges joined by a rotation and need a
nonlinear colouring [2]_; they raise :class:`NotImplementedError`.

References
----------
.. [1] O. Engler and V. Randle, *Introduction to Texture Analysis:
   Macrotexture, Microtexture, and Orientation Mapping*, 2nd ed., CRC Press
   (2010).
.. [2] G. Nolze and R. Hielscher, "Orientations -- perfectly colored",
   *J. Appl. Cryst.* **49**, 1786-1802 (2016).
"""

from __future__ import annotations

from functools import lru_cache
from itertools import combinations

import numpy as np

from crystallite.material.symmetry import (
    crystal_system,
    holohedry,
    laue_class,
    point_group_operations,
)

SAMPLE_DIRECTIONS = {"x": (1.0, 0.0, 0.0), "y": (0.0, 1.0, 0.0), "z": (0.0, 0.0, 1.0)}

_SYMMETRY_LEVELS = ("laue", "holohedry", "point_group")

# Picks the sector: off every symmetry element of every group in the standard
# setting, and inside the conventional triangles (0 <= y <= x <= z for m-3m,
# azimuth below 30 degrees for 6/mmm, ...).
_REFERENCE = np.array([0.3, 0.1, 1.0]) / np.linalg.norm([0.3, 0.1, 1.0])

_TOL = 1e-9


def _host(array):
    """NumPy copy of a NumPy or CuPy array."""
    return array.get() if hasattr(array, "get") else np.asarray(array, dtype=float)


def _normalize(vectors):
    vectors = np.asarray(vectors, dtype=float)
    return vectors / np.linalg.norm(vectors, axis=-1, keepdims=True)


def sample_direction(direction):
    """Unit sample direction from ``"x"``, ``"y"``, ``"z"`` or a 3-vector."""
    if isinstance(direction, str):
        try:
            direction = SAMPLE_DIRECTIONS[direction.lower()]
        except KeyError:
            raise ValueError(f"sample direction must be 'x', 'y', 'z' or a vector, got {direction!r}")
    return _normalize(direction)


def crystal_directions(rotations, direction="z"):
    """Crystal-frame components ``R^T s`` of the sample direction `direction`
    for each rotation in `rotations` (shape ``(..., 3, 3)``, crystal axes as
    columns). Returns shape ``(..., 3)``."""
    return np.einsum("...ji,j->...i", np.asarray(rotations, dtype=float), sample_direction(direction))


def reduce_directions(directions, operations, reference=_REFERENCE):
    """Symmetry-equivalent image of each direction closest to `reference`.

    The result lies in the Dirichlet cell of `reference`, a fundamental sector
    of the group: every direction equivalent under `operations` reduces to
    the same one (up to ties on the sector edges, whose images are equivalent
    there).

    Parameters
    ----------
    directions : array_like of shape (..., 3)
    operations : array_like of shape (n, 3, 3)
        A point group's operations (:func:`symmetry_operations`).
    reference : array_like of shape (3,)
        Must not lie on a symmetry element.

    Returns
    -------
    ndarray of shape (..., 3)
    """
    images = np.einsum("nij,...j->...ni", _host(operations), np.asarray(directions, dtype=float))
    best = np.argmax(images @ np.asarray(reference, dtype=float), axis=-1)
    return np.take_along_axis(images, best[..., None, None], axis=-2)[..., 0, :]


def symmetry_group(point_group, symmetry="laue"):
    """Point group applied at a symmetry level: the point group's Laue class
    (``"laue"``), its crystal system's holohedry (``"holohedry"``) or the
    point group itself (``"point_group"``)."""
    if symmetry == "laue":
        return laue_class(point_group)
    if symmetry == "holohedry":
        return holohedry(point_group)
    if symmetry == "point_group":
        point_group_operations(point_group)  # validates point_group
        return point_group
    raise ValueError(f"symmetry must be one of {_SYMMETRY_LEVELS}, got {symmetry!r}")


def symmetry_operations(point_group, symmetry="laue"):
    """Operations of :func:`symmetry_group`, a NumPy array ``(n, 3, 3)``."""
    return _host(point_group_operations(symmetry_group(point_group, symmetry)))


def _mirror_normals(operations):
    """Unit normals of the mirror planes among `operations`, oriented towards
    the reference direction."""
    normals = []
    for op in operations:
        if np.linalg.det(op) < 0 and abs(np.trace(op) - 1.0) < 1e-6:
            # op = I - 2 n n^T
            projector = (np.eye(3) - op) / 2.0
            n = projector[:, np.argmax(np.linalg.norm(projector, axis=0))]
            n = n / np.linalg.norm(n)
            normals.append(n if n @ _REFERENCE > 0 else -n)
    return np.array(normals).reshape(-1, 3)


def _chamber_vertices(normals):
    """Vertices of the region ``n . d >= 0`` for every mirror normal ``n``."""
    vertices = []
    for a, b in combinations(normals, 2):
        cross = np.cross(a, b)
        if np.linalg.norm(cross) < 1e-9:
            continue
        for candidate in (cross, -cross):
            candidate = candidate / np.linalg.norm(candidate)
            if np.all(normals @ candidate > -1e-9) and not any(
                np.allclose(candidate, v, atol=1e-9) for v in vertices
            ):
                vertices.append(candidate)
    return np.array(vertices).reshape(-1, 3)


def _slerp(a, b, n):
    """`n` points along the great-circle arc from `a` to `b`."""
    angle = np.arccos(np.clip(a @ b, -1.0, 1.0))
    t = np.linspace(0.0, 1.0, n)[:, None]
    return (np.sin((1 - t) * angle) * a + np.sin(t * angle) * b) / np.sin(angle)


def spherical_triangle_area(vertices):
    """Area (spherical excess) of the spherical triangle with unit `vertices`
    (Van Oosterom and Strackee)."""
    a, b, c = _normalize(vertices)
    return 2.0 * np.arctan2(abs(a @ np.cross(b, c)), 1.0 + a @ b + b @ c + c @ a)


def spherical_triangle_centroid(vertices):
    r"""Unit direction of the area centroid of a spherical triangle,
    :math:`\int d\,dA \propto \sum_{\text{edges }ab}\theta_{ab}\,
    \widehat{a\times b}` (edges counterclockwise seen from outside)."""
    v = _normalize(vertices)
    if np.linalg.det(v) < 0:
        v = v[::-1]
    total = np.zeros(3)
    for a, b in zip(v, np.roll(v, -1, axis=0)):
        cross = np.cross(a, b)
        total += np.arccos(np.clip(a @ b, -1.0, 1.0)) * cross / np.linalg.norm(cross)
    return total / np.linalg.norm(total)


def _integer_indices(values, tol=1e-6):
    values = np.asarray(values, dtype=float)
    base = values / np.abs(values[np.abs(values) > tol]).min()
    for multiple in range(1, 7):
        scaled = base * multiple
        if np.allclose(scaled, np.round(scaled), atol=1e-4):
            return np.round(scaled).astype(int)
    return np.round(base, 2)


def miller_label(direction, hexagonal=False):
    r"""Direction indices of a Cartesian `direction` as a TeX string (bars
    for negative indices): three-index ``[uvw]`` along the crystal axes, or
    four-index Miller--Bravais ``[UVTW]`` with :math:`a_1` along x when
    `hexagonal`. The axes are taken orthonormal (with :math:`c/a=1` for
    `hexagonal`), which labels the sector vertices exactly: each lies along
    a crystal axis, in a basal or prism plane, or along a cube diagonal."""
    d = _normalize(direction)
    if hexagonal:
        basal = np.array([[1.0, 0.0], [-0.5, 3**0.5 / 2], [-0.5, -(3**0.5) / 2]])
        indices = _integer_indices([*(2.0 / 3.0 * basal @ d[:2]), d[2]])
    else:
        indices = _integer_indices(d)
    parts = [rf"\bar{{{-i}}}" if i < 0 else str(i) for i in indices]
    return "$" + "".join(parts) + "$"


class InversePoleFigure:
    """Fundamental sector and IPF colour key of a point group.

    Parameters
    ----------
    point_group : str
        One of the 32 point groups, e.g. ``"m-3m"``, ``"6/mmm"``, ``"-43m"``.
    symmetry : {"laue", "holohedry", "point_group"}
        Level at which the point group's symmetry is applied (see the module
        docstring).

    Attributes
    ----------
    group : str
        The point group whose operations reduce the directions.
    operations : ndarray of shape (n, 3, 3)
    vertices : ndarray of shape (3, 3)
        Sector vertices, in red, green, blue order: the vertex nearest the
        crystal z axis is red, the other two green and blue by increasing
        azimuth.
    white_point : ndarray of shape (3,)
        The sector's area centroid, coloured white.
    labels : list of str
        Direction indices of the vertices (:func:`miller_label`).

    Raises
    ------
    NotImplementedError
        If the group's sector is not a triangle bounded by mirror planes.
    """

    def __init__(self, point_group, symmetry="laue"):
        self.point_group = point_group
        self.symmetry = symmetry
        self.group = symmetry_group(point_group, symmetry)
        self.operations = symmetry_operations(point_group, symmetry)

        # The mirrors bound a triangle; it is a fundamental sector (the mirrors
        # generate the whole group) when its area is that of one.
        vertices = _chamber_vertices(_mirror_normals(self.operations))
        if len(vertices) != 3 or not np.isclose(
            spherical_triangle_area(vertices), 4.0 * np.pi / len(self.operations)
        ):
            raise NotImplementedError(
                f"point group {self.group!r} (from {point_group!r} at the "
                f"{symmetry!r} level) has no triangular sector bounded by "
                "mirror planes; its nonlinear colour key is not implemented"
            )

        red = np.argmax(vertices[:, 2])
        others = [i for i in range(3) if i != red]
        others.sort(key=lambda i: np.arctan2(vertices[i, 1], vertices[i, 0]))
        self.vertices = vertices[[red, *others]]

        # Row i: normal of the edge opposite vertex i, scaled so that it
        # evaluates to 1 at vertex i (and 0 on that edge).
        planes = np.cross(np.roll(self.vertices, -1, axis=0), np.roll(self.vertices, -2, axis=0))
        self._planes = planes / np.einsum("ij,ij->i", planes, self.vertices)[:, None]
        self.white_point = spherical_triangle_centroid(self.vertices)
        self._weights = 1.0 / (self._planes @ self.white_point)

        hexagonal = crystal_system(self.group) in ("trigonal", "hexagonal")
        self.labels = [miller_label(v, hexagonal) for v in self.vertices]

    def __repr__(self):
        return f"InversePoleFigure({self.point_group!r}, symmetry={self.symmetry!r})"

    def reduce(self, directions):
        """Unit symmetry-equivalent of each direction inside the sector,
        shape ``(..., 3)``."""
        return reduce_directions(_normalize(directions), self.operations)

    def contains(self, directions, tol=1e-9):
        """Whether each unit direction lies in the sector (without reduction)."""
        return np.all(np.asarray(directions, dtype=float) @ self._planes.T >= -tol, axis=-1)

    def color(self, directions):
        """RGB in [0, 1] of each crystal direction, shape ``(..., 3)``."""
        channels = np.clip(self.reduce(directions) @ self._planes.T, 0.0, None) * self._weights
        return channels / channels.max(axis=-1, keepdims=True)

    def project(self, directions):
        """Stereographic coordinates (from the -z pole) of the reduced
        directions, shape ``(..., 2)``."""
        d = self.reduce(directions)
        return d[..., :2] / (1.0 + d[..., 2:3])

    def outline(self, n=64):
        """Closed stereographic outline of the sector, shape ``(3 n + 1, 2)``."""
        arcs = [
            _slerp(a, b, n)[:-1]
            for a, b in zip(self.vertices, np.roll(self.vertices, -1, axis=0))
        ]
        points = np.concatenate(arcs + [self.vertices[:1]])
        return points[:, :2] / (1.0 + points[:, 2:3])

    def key_image(self, resolution=256):
        """Rasterized colour key: RGBA over the sector's stereographic
        bounding box, transparent outside it, coloured by :meth:`color`.

        Returns
        -------
        image : ndarray of shape (ny, nx, 4)
            Row 0 at the bottom (``imshow(..., origin="lower")``).
        extent : tuple
            ``(x0, x1, y0, y1)`` in stereographic coordinates.
        """
        outline = self.outline()
        (x0, y0), (x1, y1) = outline.min(axis=0), outline.max(axis=0)
        step = max(x1 - x0, y1 - y0) / resolution
        nx = max(int(np.ceil((x1 - x0) / step)), 1)
        ny = max(int(np.ceil((y1 - y0) / step)), 1)
        x = x0 + (np.arange(nx) + 0.5) * (x1 - x0) / nx
        y = y0 + (np.arange(ny) + 0.5) * (y1 - y0) / ny
        directions = inverse_stereographic(*np.meshgrid(x, y))
        image = np.zeros((ny, nx, 4))
        inside = self.contains(directions)
        image[inside, :3] = self.color(directions[inside])
        image[inside, 3] = 1.0
        return image, (x0, x1, y0, y1)


def inverse_stereographic(x, y):
    """Unit directions (upper hemisphere) of stereographic coordinates
    projected from the -z pole, shape ``x.shape + (3,)``."""
    x, y = np.asarray(x, dtype=float), np.asarray(y, dtype=float)
    r2 = x * x + y * y
    return np.stack([2.0 * x, 2.0 * y, 1.0 - r2], axis=-1) / (1.0 + r2)[..., None]


@lru_cache(maxsize=None)
def inverse_pole_figure(point_group, symmetry="laue"):
    """Cached :class:`InversePoleFigure`."""
    return InversePoleFigure(point_group, symmetry)


def _as_ipf(ipf, symmetry="laue"):
    return ipf if isinstance(ipf, InversePoleFigure) else inverse_pole_figure(ipf, symmetry)


def ipf_color(directions, point_group, symmetry="laue"):
    """IPF colour of crystal directions (shape ``(..., 3)``) for a point group
    at a symmetry level; see :class:`InversePoleFigure`."""
    return inverse_pole_figure(point_group, symmetry).color(directions)


def orientation_colors(rotations, ipf, direction="z", symmetry="laue"):
    """IPF colour of each orientation along a sample direction.

    Parameters
    ----------
    rotations : array_like of shape (..., 3, 3)
        Crystal axes as columns, in the sample frame.
    ipf : InversePoleFigure or str
        The colour key, or a point group (with `symmetry`).
    direction : {"x", "y", "z"} or array_like of shape (3,)
        Sample direction.

    Returns
    -------
    ndarray of shape (..., 3)
    """
    return _as_ipf(ipf, symmetry).color(crystal_directions(rotations, direction))


def orientation_map(labels, rotations, ipf, direction="z", symmetry="laue"):
    """IPF-coloured image of a labelled microstructure: one colour per
    orientation, placed by the integer `labels`.

    Parameters
    ----------
    labels : array_like of int
        Index into `rotations` at every voxel: ``ms.grain_ids`` with
        ``ms.orientations``, ``ms.slot_field()`` with ``ms.slot_orientations``,
        or ``eta.argmax(axis=0)`` for order parameters ``eta`` that carry
        ``ms.slot_orientations``.
    rotations : array_like of shape (n, 3, 3)
    ipf, direction, symmetry
        As in :func:`orientation_colors`.

    Returns
    -------
    ndarray of shape ``labels.shape + (3,)``
    """
    return orientation_colors(rotations, ipf, direction, symmetry)[_host(labels).astype(int)]


# --- plotting ---------------------------------------------------------------


def _pyplot():
    try:
        import matplotlib.pyplot as plt
    except ImportError as error:
        raise ImportError("plotting requires the optional matplotlib dependency") from error
    return plt


def _sector_axes(ipf, ax, labels=True):
    """Outline and vertex labels of the sector on `ax`."""
    outline = ipf.outline()
    ax.plot(outline[:, 0], outline[:, 1], color="k", linewidth=1.0)
    if labels:
        span = np.ptp(outline, axis=0).max()
        center = ipf.project(ipf.white_point)
        for vertex, label in zip(ipf.project(ipf.vertices), ipf.labels):
            offset = vertex - center
            offset = 0.07 * span * offset / np.linalg.norm(offset)
            ax.text(*(vertex + offset), label, ha="center", va="center")
    ax.set_aspect("equal")
    ax.set_axis_off()
    return ax


def plot_ipf_key(ipf, ax=None, resolution=256, labels=True, symmetry="laue"):
    """Draw the IPF colour key of `ipf` (an :class:`InversePoleFigure` or a
    point group), coloured by the same :meth:`InversePoleFigure.color` as the
    orientation maps. Returns the axes."""
    ipf = _as_ipf(ipf, symmetry)
    if ax is None:
        ax = _pyplot().subplots()[1]
    image, extent = ipf.key_image(resolution)
    ax.imshow(image, origin="lower", extent=extent, interpolation="nearest")
    return _sector_axes(ipf, ax, labels)


def plot_ipf(rotations, ipf, direction="z", ax=None, labels=True, symmetry="laue", **scatter):
    """Scatter the sample direction `direction` of each orientation in the
    fundamental sector (an inverse pole figure). Extra keywords go to
    :meth:`matplotlib.axes.Axes.scatter`. Returns the axes."""
    ipf = _as_ipf(ipf, symmetry)
    if ax is None:
        ax = _pyplot().subplots()[1]
    points = ipf.project(crystal_directions(rotations, direction)).reshape(-1, 2)
    scatter.setdefault("s", 12)
    ax.scatter(points[:, 0], points[:, 1], **scatter)
    return _sector_axes(ipf, ax, labels)


def _boundary_mask(labels):
    """Voxels whose label differs from a (periodic) neighbour's."""
    mask = np.zeros(labels.shape, dtype=bool)
    for axis in range(labels.ndim):
        if labels.shape[axis] > 1:
            mask |= labels != np.roll(labels, 1, axis=axis)
    return mask


def plot_orientation_map(
    labels,
    rotations,
    ipf,
    direction="z",
    ax=None,
    extent=None,
    boundaries=True,
    z_index=0,
    symmetry="laue",
):
    """Draw an IPF orientation map (see :func:`orientation_map`) of a 2D
    microstructure, or of the slice `z_index` of a 3D one, with x to the
    right and y up. `extent` is passed to ``imshow`` (e.g. ``(0, Lx, 0, Ly)``);
    `boundaries` blacks out voxels on label boundaries. Returns the axes."""
    labels = _host(labels).astype(int)
    if labels.ndim == 3:
        labels = labels[:, :, z_index]
    rgb = orientation_map(labels, rotations, ipf, direction, symmetry)
    if boundaries:
        rgb[_boundary_mask(labels)] = 0.0
    if ax is None:
        ax = _pyplot().subplots()[1]
    ax.imshow(np.swapaxes(rgb, 0, 1), origin="lower", extent=extent, interpolation="nearest")
    ax.set_xticks([])
    ax.set_yticks([])
    return ax


def plot_orientation_maps(
    labels, rotations, ipf, directions="xyz", key=True, extent=None, boundaries=True,
    z_index=0, symmetry="laue",
):
    """Orientation maps along several sample directions side by side, with
    the colour key. Returns ``(figure, axes)``."""
    ipf = _as_ipf(ipf, symmetry)
    plt = _pyplot()
    n = len(directions) + bool(key)
    figure, axes = plt.subplots(1, n, figsize=(3.2 * n, 3.4), squeeze=False)
    axes = axes[0]
    for ax, direction in zip(axes, directions):
        plot_orientation_map(
            labels, rotations, ipf, direction, ax=ax, extent=extent,
            boundaries=boundaries, z_index=z_index,
        )
        name = direction if isinstance(direction, str) else str(list(direction))
        ax.set_title(f"IPF-{name.upper()}")
    if key:
        plot_ipf_key(ipf, ax=axes[-1])
    figure.tight_layout()
    return figure, axes
