import numpy as np
import spglib

from crystallite.backend import xp

_INVERSION = -np.eye(3)


def _rotation(axis, degrees):
    """Proper rotation matrix by `degrees` about `axis` (Rodrigues formula)."""
    n = np.asarray(axis, dtype=float)
    n = n / np.linalg.norm(n)
    theta = np.radians(degrees)
    k = np.array(
        [[0, -n[2], n[1]], [n[2], 0, -n[0]], [-n[1], n[0], 0]]
    )
    return np.eye(3) + np.sin(theta) * k + (1 - np.cos(theta)) * (k @ k)


def _mirror(normal):
    """Reflection matrix through the plane with the given normal."""
    n = np.asarray(normal, dtype=float)
    n = n / np.linalg.norm(n)
    return np.eye(3) - 2 * np.outer(n, n)


_X, _Y, _Z = (1, 0, 0), (0, 1, 0), (0, 0, 1)
_DIAG3 = (1, 1, 1)
_DIAG2 = (1, 1, 0)


def _close_group(generators, tol=1e-6):
    """Full set of operations generated by `generators` under composition."""
    ops = [np.eye(3)]

    def add(candidate):
        for op in ops:
            if np.allclose(op, candidate, atol=tol):
                return False
        ops.append(candidate)
        return True

    for g in generators:
        add(np.asarray(g, dtype=float))

    changed = True
    while changed:
        changed = False
        for a in list(ops):
            for b in list(ops):
                if add(a @ b):
                    changed = True

    return np.stack(ops, axis=0)


_C2X, _C2Y, _C2Z = _rotation(_X, 180), _rotation(_Y, 180), _rotation(_Z, 180)
_C3Z, _C4Z, _C6Z = _rotation(_Z, 120), _rotation(_Z, 90), _rotation(_Z, 60)
_C3_111 = _rotation(_DIAG3, 120)
_MX, _MY, _MZ = _mirror(_X), _mirror(_Y), _mirror(_Z)
_S4Z, _S6Z = -_rotation(_Z, 90), -_rotation(_Z, 60)

_GENERATORS = {
    "1": (),
    "-1": (_INVERSION,),
    "2": (_C2Y,),
    "m": (_MY,),
    "2/m": (_C2Y, _INVERSION),
    "222": (_C2Z, _C2X),
    "mm2": (_C2Z, _MX),
    "mmm": (_C2Z, _C2X, _INVERSION),
    "4": (_C4Z,),
    "-4": (_S4Z,),
    "4/m": (_C4Z, _INVERSION),
    "422": (_C4Z, _C2X),
    "4mm": (_C4Z, _MX),
    "-42m": (_S4Z, _C2X),
    "-4m2": (_S4Z, _MX),
    "4/mmm": (_C4Z, _C2X, _INVERSION),
    "3": (_C3Z,),
    "-3": (_C3Z, _INVERSION),
    "32": (_C3Z, _C2X),
    "3m": (_C3Z, _MX),
    "-3m": (_C3Z, _C2X, _INVERSION),
    "6": (_C6Z,),
    "-6": (_S6Z,),
    "6/m": (_C6Z, _INVERSION),
    "622": (_C6Z, _C2X),
    "6mm": (_C6Z, _MX),
    "-6m2": (_S6Z, _MX),
    "-62m": (_S6Z, _C2X),
    "6/mmm": (_C6Z, _C2X, _INVERSION),
    "23": (_C2Z, _C3_111),
    "m-3": (_C2Z, _C3_111, _INVERSION),
    "432": (_C4Z, _C3_111),
    "-43m": (_S4Z, _C3_111),
    "m-3m": (_C4Z, _C3_111, _INVERSION),
}

_EXPECTED_ORDER = {
    "1": 1, "-1": 2, "2": 2, "m": 2, "2/m": 4,
    "222": 4, "mm2": 4, "mmm": 8,
    "4": 4, "-4": 4, "4/m": 8, "422": 8, "4mm": 8,
    "-42m": 8, "-4m2": 8, "4/mmm": 16,
    "3": 3, "-3": 6, "32": 6, "3m": 6, "-3m": 12,
    "6": 6, "-6": 6, "6/m": 12, "622": 12, "6mm": 12,
    "-6m2": 12, "-62m": 12, "6/mmm": 24,
    "23": 12, "m-3": 24, "432": 24, "-43m": 24, "m-3m": 48,
}

_operations_cache = {}


def point_group_operations(point_group):
    """(n, 3, 3) Cartesian rotation/reflection matrices for `point_group`.

    `n` is the group order. Standard setting: principal axis along z,
    secondary two-fold/mirror along x, monoclinic unique axis along y,
    cubic tertiary axis along [111].
    """
    if point_group not in _GENERATORS:
        raise ValueError(f"unrecognized point group: {point_group!r}")

    if point_group not in _operations_cache:
        ops = _close_group(_GENERATORS[point_group])
        expected = _EXPECTED_ORDER[point_group]
        if len(ops) != expected:
            raise RuntimeError(
                f"point group {point_group!r}: generated {len(ops)} "
                f"operations, expected {expected}"
            )
        _operations_cache[point_group] = xp.asarray(ops)

    return _operations_cache[point_group]


def symmetrize(
    tensor, operations, time_reversals=None, axial_axes=(), time_reversal_odd=False
):
    r"""Group-average a Cartesian tensor of any rank (Neumann's principle).

    Projects `tensor` onto the subspace invariant under every operation,
    i.e. the physically allowed form for a property tensor of a crystal
    with those (magnetic) point-group operations.

    `axial_axes` marks tensor axes that are pseudovector/axial legs
    (e.g. a magnetic-field index): each contributes an extra
    :math:`\det(R)` sign under an operation `R`. `time_reversal_odd`
    marks the tensor itself as odd under time reversal (e.g. it couples
    to magnetization linearly rather than quadratically): operations
    flagged anti-time-reversal in `time_reversals` (spglib convention:
    1 = anti-time-reversal) then contribute with a sign flip.
    """
    if time_reversals is None:
        time_reversals = xp.zeros(len(operations))

    total = xp.zeros_like(tensor)
    for op, reversed_ in zip(operations, time_reversals):
        rotated = tensor
        for axis in range(tensor.ndim):
            rotated = xp.moveaxis(
                xp.tensordot(op, rotated, axes=([1], [axis])), 0, axis
            )
        sign = 1.0
        if axial_axes:
            sign *= float(xp.linalg.det(op)) ** len(axial_axes)
        if time_reversal_odd and reversed_:
            sign *= -1.0
        total = total + sign * rotated
    return total / len(operations)


_CRYSTAL_SYSTEM_LATTICE = {
    "triclinic": np.eye(3),
    "monoclinic": np.eye(3),
    "orthorhombic": np.eye(3),
    "tetragonal": np.eye(3),
    "cubic": np.eye(3),
    "trigonal": np.array(
        [[1.0, -0.5, 0.0], [0.0, 3**0.5 / 2, 0.0], [0.0, 0.0, 1.0]]
    ),
    "hexagonal": np.array(
        [[1.0, -0.5, 0.0], [0.0, 3**0.5 / 2, 0.0], [0.0, 0.0, 1.0]]
    ),
}
"""Idealized (unit-length) lattice per crystal system, columns = a, b, c.

Only axis *directions/angles* matter for converting a fractional point
operation to Cartesian, not the actual cell lengths, so idealized cells
give exact results.
"""


def _crystal_system(spacegroup_number):
    if spacegroup_number <= 2:
        return "triclinic"
    if spacegroup_number <= 15:
        return "monoclinic"
    if spacegroup_number <= 74:
        return "orthorhombic"
    if spacegroup_number <= 142:
        return "tetragonal"
    if spacegroup_number <= 167:
        return "trigonal"
    if spacegroup_number <= 194:
        return "hexagonal"
    return "cubic"


_magnetic_operations_cache = {}


def magnetic_point_group_operations(uni_number, tol=1e-6):
    """(n, 3, 3) Cartesian ops + (n,) time-reversal flags for the magnetic
    point group underlying spglib magnetic-space-group database entry
    `uni_number` (1..1651), reduced to distinct (rotation, time-reversal)
    pairs -- i.e. translations are dropped, which is all Neumann's
    principle for a macroscopic property tensor ever sees.

    Time-reversal flags follow spglib: 1 marks an anti-time-reversal
    ("primed") operation. Look up `uni_number` via
    `spglib.get_magnetic_spacegroup_type` (BNS/OG/Litvin numbering) or
    `list_magnetic_point_groups`.
    """
    if uni_number in _magnetic_operations_cache:
        return _magnetic_operations_cache[uni_number]

    info = spglib.get_magnetic_spacegroup_type(uni_number)
    if info is None:
        raise ValueError(f"unrecognized magnetic uni_number: {uni_number!r}")
    data = spglib.get_magnetic_symmetry_from_database(uni_number)

    lattice = _CRYSTAL_SYSTEM_LATTICE[_crystal_system(info.number)]
    inv_lattice = np.linalg.inv(lattice)

    ops, flags = [], []
    for r_frac, reversed_ in zip(data["rotations"], data["time_reversals"]):
        r_cart = lattice @ r_frac @ inv_lattice
        if not any(
            f == reversed_ and np.allclose(o, r_cart, atol=tol)
            for o, f in zip(ops, flags)
        ):
            ops.append(r_cart)
            flags.append(reversed_)

    result = (
        xp.asarray(np.stack(ops)),
        xp.asarray(np.asarray(flags, dtype=float)),
    )
    _magnetic_operations_cache[uni_number] = result
    return result


def list_magnetic_point_groups(point_group):
    """Magnetic point groups whose unprimed operations are `point_group`.

    Scans all 1651 spglib magnetic-space-group database entries and
    returns, for each whose rotation set (ignoring time reversal)
    matches `point_group_operations(point_group)`, a dict with
    `uni_number`, `bns_number`, and `type` (1=colorless/ordinary,
    2=grey, 3=black-white, 4=translation-doubled -- see
    `magnetic_point_group_operations`).
    """
    target = point_group_operations(point_group)
    matches = []
    for uni_number in range(1, 1652):
        ops, _ = magnetic_point_group_operations(uni_number)
        distinct = []
        for op in ops:
            if not any(np.allclose(op, d, atol=1e-6) for d in distinct):
                distinct.append(op)
        if len(distinct) != len(target):
            continue
        if all(
            any(np.allclose(op, t, atol=1e-6) for t in target) for op in distinct
        ):
            info = spglib.get_magnetic_spacegroup_type(uni_number)
            matches.append(
                {
                    "uni_number": uni_number,
                    "bns_number": info.bns_number,
                    "type": info.type,
                }
            )
    return matches
