"""Inverse-pole-figure colour keys of all 32 point groups, one row per crystal
system, from :class:`crystallite.visualization.orientation.InversePoleFigure`
at the ``"point_group"`` symmetry level.

Groups generated by their mirror planes have a single key, white at the
centre of the sector. The others split the sector into a white half and a
black half (Nolze and Hielscher). ``-1``, ``-3`` and ``-4``, which have no
continuous one-to-one key, take the key of their proper rotation subgroup.
Sectors of polar groups reach into the lower hemisphere and are drawn as an
upper and a lower panel.

Plots use the project's shared style,
:func:`crystallite.visualization.configure_pgf`.
"""

from __future__ import annotations

import re

from crystallite.material.symmetry import _POINT_GROUPS_BY_SYSTEM
from crystallite.visualization.orientation import InversePoleFigure, plot_ipf_key


def symbol(point_group):
    """TeX Hermann--Mauguin symbol, with bars for rotoinversions."""
    return "$" + re.sub(r"-(\d)", r"\\bar{\1}", point_group) + "$"


def run_example(resolution=200, save_path=None, show_plot=False):
    """Draw the colour keys of all point groups.

    Returns
    -------
    dict
        The :class:`InversePoleFigure` of each point group.
    """
    keys = {
        point_group: InversePoleFigure(point_group, "point_group")
        for groups in _POINT_GROUPS_BY_SYSTEM.values()
        for point_group in groups
    }

    if save_path is not None or show_plot:
        try:
            from crystallite.visualization import configure_pgf

            plt = configure_pgf()
        except ImportError:  # pragma: no cover
            print("Matplotlib is not installed; skipping plot output for this run.")
            return keys

        rows = list(_POINT_GROUPS_BY_SYSTEM.items())
        columns = max(len(groups) for _, groups in rows)
        fig, axes = plt.subplots(len(rows), columns, figsize=(2.9 * columns, 2.9 * len(rows)))
        for ax in axes.flat:
            ax.set_axis_off()
        for row, (system, groups) in enumerate(rows):
            axes[row, 0].text(
                -0.35, 0.5, system, transform=axes[row, 0].transAxes, rotation=90,
                ha="center", va="center", fontsize=14,
            )
            for ax, point_group in zip(axes[row], groups):
                ipf = keys[point_group]
                plot_ipf_key(ipf, ax=ax, resolution=resolution)
                for label in ax.texts:
                    label.set_fontsize(8)
                if ipf.group != point_group:
                    kind = f"as {symbol(ipf.group)}"
                elif ipf.mirror is None:
                    kind = "mirror group"
                else:
                    kind = "white/black halves"
                ax.set_title(f"{symbol(point_group)}\n{kind}", fontsize=12, linespacing=1.3)
        fig.tight_layout(rect=(0.02, 0.0, 1.0, 1.0))
        if save_path is not None:
            fig.savefig(save_path, dpi=150, bbox_inches="tight")
            print(f"Saved plot to {save_path}")
        if show_plot:
            plt.show()
        plt.close(fig)
    return keys


if __name__ == "__main__":
    run_example(save_path="point_group_keys.png")
